services:
  adguardhome:
    image: ghcr.io/rafaelfgomes/adguardhome
    container_name: adguardhome-app
    hostname: adguardhome
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ./data/adguardhome/work:/opt/adguardhome/work
      - ./data/adguardhome/config:/opt/adguardhome/conf
    restart: unless-stopped
    ports:
      - '53:53'
      - '80:80/tcp'
      - '443:443/tcp'
      - '784:784/udp'
      - '853:853'
      - '3000:3000/tcp'
      - '5443:5443'
      - '8853:8853/udp'
    networks:
      local:

  backup:
    image: ghcr.io/rafaelfgomes/syncthing
    container_name: adguardhome-backup
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ./data/syncthing/config:/var/syncthing
      - ./data/adguardhome:/data
    restart: unless-stopped
    ports:
      - '8384:8384'
      - '22000:22000/tcp'
      - '22000:22000/udp'
      - '21027:21027/udp'
    networks:
      local:

networks:
  local:
    name: adguardhome-local-network