services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    hostname: adguardhome
    volumes:
      - ./data/config:/opt/adguardhome/conf
      - ./data/work:/opt/adguardhome/work
    environment:
      - TZ=${TIMEZONE:-Etc/UTC}
    restart: unless-stopped
    network_mode: host