services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    hostname: adguardhome
    volumes:
      - ${ADGUARDHOME_CONFIG_FOLDER:-./config}:/opt/adguardhome/conf
      - ${ADGUARDHOME_WORK_FOLDER:-./work}:/opt/adguardhome/work
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - '53:53/tcp' #DNS
      - '53:53/udp' #DNS
      - '${HTTP_PORT:-80}:80'
      - '${HTTPS_PORT:-443}:443'
      - '${SETUP_PORT:-3000}:3000'
      - '853:853/tcp' #DNS-over-TLS (DoT)
      - '853:853/udp' #DNS-over-QUIC (DoQ)
      - '784:784/udp' #DNS-over-QUIC (DoQ)
      - '8853:8853/udp' #DNS-over-QUIC (DoQ)
      - '5443:5443/tcp' #DNSCrypt Server
      - '5443:5443/udp' #DNSCrypt Server
    networks:
      - local

networks:
  local:
    name: adguard-network